### PR TITLE
Qubes-Whonix 16

### PR DESCRIPTION
**Pull request by adrelanos**

### CODE REVIEW

**Comment by marmarek** [comment]
You remove Whonix 15 here, and I don't see a branch with Whonix 15 configs left. Does it mean you don't expect any Whonix 15 builds anymore? What should we include in upcoming Qubes R4.1 and also further point releases of Qubes R4.0? I guess Whonix 16 already, right?
I'm fine with that, but we may need to adjust release schedules - to ensure that final Whonix 16 release happens before final R4.1.

**Comment by adrelanos** [comment]
> You remove Whonix 15 here, and I don't see a branch with Whonix 15 configs left. Does it mean you don't expect any Whonix 15 builds anymore?

No more Whonix 15 builds expected indeed.

> What should we include in upcoming Qubes R4.1 and also further point releases of Qubes R4.0? I guess Whonix 16 already, right?

Whonix 16 if possible...

> I'm fine with that, but we may need to adjust release schedules - to ensure that final Whonix 16 release happens before final R4.1.

Whonix 15 in R4.1 if Whonix 15 would then very soon deprecated would be unfortunate. I am not aware of any Qubes R4.1 ETA? Does Qubes R4.1 happen sooner than in 1 or 2 months? Hope that's not a trick question. So maybe answering this in another way even though I usually don't give an ETA either. Whonix 16 is my main focus now. I hope testers images are available in less than 1 month. Qubes-Whonix 16 shouldn't be too hard. Since my release upgrade Qubes-Whonix 15 -> Qubes-Whonix 16 first impression is great, I would wonder if new builds would have many release blockers.

**Comment by adrelanos** [comment]
Non-Qubes-Whonix 16 (Debian `bullseye` based) testers-only release:
https://forums.whonix.org/t/whonix-16-0-0-8-debian-11-bullseye-based-for-virtualbox-major-release-testers-wanted/12190

If there's no blocker, please merge so Qubes-Whonix 16 testers-only build can be created.

**Comment by marmarek** [comment]
Sure, I'll merge. But in fact it isn't necessary. The Whonix template build uses the repository from @Whonix directly (see https://github.com/QubesOS/qubes-template-configs/blob/master/R4.1/templates-community/whonix-15.conf). I'll adjust for Whonix 16 in a moment.

**Pull request merged**
