### PR TITLE
update

### PR DESCRIPTION
**Pull request by adrelanos**

### CODE REVIEW

**Comment by marmarek** [comment]
You don't need to update this repo, [templates are built directly from Whonix one](https://github.com/QubesOS/qubes-template-configs/blob/master/R4.0/templates-community/whonix-15.conf#L25)

**Comment by marmarek** [comment]
I'm not really sure why this repo is only at my github account and not @QubesOS. I'll move it there. But can you add to the README info where is the canonical location (whether that is @Whonix, @adrelanos, or maybe even gitlab one?)

**Comment by adrelanos** [comment]
https://www.qubes-os.org/news/2021/02/28/improvements-in-testing-and-building/

> In the broader future, our ultimate goal is to make all parts of Qubes OS reproducible, including templates and the installation image.

I guess long term then it needs to be under @QubesOS anyhow?

**Comment by marmarek** [comment]
I don't see how is it related?

**Comment by adrelanos** [comment]
I guess if the goal is to have all parts of Qubes OS reproducible, it makes sense to have all parts as far as building binaries is concerned under exclusive control by Qubes OS.

If Qubes OS is completely reproducible, it would be a weakness if deleting/moving a Whonix github repository (a year later or so) would result in Qubes no longer being reproducible since the source code download would fail.

**Comment by marmarek** [comment]
Qubes OS is in fact mostly a collection of a lot of 3rd-party components, and we do work with other projects (like Debian, Fedora, etc) to achieve reproducibility (including preserving access to old sources and binaries). So, I don't see why Whonix should be any special here.

**Pull request merged**
